const { ENV_DEFAULTS, ENV_KEYS, envBoolean, envInteger, envString } = require("../../config/env");

function getControlBoardConfig() {
  const CONTROL_BOARD_TRANSPORT = ENV_KEYS.CONTROL_BOARD_TRANSPORT;
  const CONTROL_BOARD_HOST = ENV_KEYS.CONTROL_BOARD_HOST;
  const CONTROL_BOARD_PORT = ENV_KEYS.CONTROL_BOARD_PORT;
  const CONTROL_BOARD_CONNECT_TIMEOUT_MS = ENV_KEYS.CONTROL_BOARD_CONNECT_TIMEOUT_MS;
  const CONTROL_BOARD_RESPONSE_TIMEOUT_MS = ENV_KEYS.CONTROL_BOARD_RESPONSE_TIMEOUT_MS;
  const CONTROL_BOARD_RETRY_COUNT = ENV_KEYS.CONTROL_BOARD_RETRY_COUNT;
  const CONTROL_BOARD_HEARTBEAT_INTERVAL_MS = ENV_KEYS.CONTROL_BOARD_HEARTBEAT_INTERVAL_MS;
  const CONTROL_BOARD_DRY_RUN = ENV_KEYS.CONTROL_BOARD_DRY_RUN;
  const CONTROL_BOARD_LIVE_APPROVED = ENV_KEYS.CONTROL_BOARD_LIVE_APPROVED;

  return {
    transport: envString(CONTROL_BOARD_TRANSPORT, ENV_DEFAULTS.CONTROL_BOARD_TRANSPORT).toLowerCase(),
    host: envString(CONTROL_BOARD_HOST, ENV_DEFAULTS.CONTROL_BOARD_HOST),
    port: envInteger(CONTROL_BOARD_PORT, ENV_DEFAULTS.CONTROL_BOARD_PORT, { min: 0 }),
    connectTimeoutMs: envInteger(CONTROL_BOARD_CONNECT_TIMEOUT_MS, ENV_DEFAULTS.CONTROL_BOARD_CONNECT_TIMEOUT_MS, { min: 0 }),
    responseTimeoutMs: envInteger(CONTROL_BOARD_RESPONSE_TIMEOUT_MS, ENV_DEFAULTS.CONTROL_BOARD_RESPONSE_TIMEOUT_MS, { min: 0 }),
    retryCount: envInteger(CONTROL_BOARD_RETRY_COUNT, ENV_DEFAULTS.CONTROL_BOARD_RETRY_COUNT, { min: 0 }),
    heartbeatIntervalMs: envInteger(CONTROL_BOARD_HEARTBEAT_INTERVAL_MS, ENV_DEFAULTS.CONTROL_BOARD_HEARTBEAT_INTERVAL_MS, { min: 0 }),
    dryRun: envBoolean(CONTROL_BOARD_DRY_RUN, ENV_DEFAULTS.CONTROL_BOARD_DRY_RUN),
    liveApproved: envBoolean(CONTROL_BOARD_LIVE_APPROVED, ENV_DEFAULTS.CONTROL_BOARD_LIVE_APPROVED),
  };
}

module.exports = {
  getControlBoardConfig,
};
